### ISSUE TITLE
Craft 4 Install

### ISSUE THREAD

**Issue by clarisse-catacutan** [KuriousAgency/craft-qrcode#10]
We just recently updated our Craft CMS to v4 and are now trying to install QRCode but are all having the same errors.

![image](https://user-images.githubusercontent.com/76716263/219525415-e2e3783e-9692-446a-b615-be10c023d804.png)

We also installed several plugins after updating to v4 and they all went smoothly except for this one.

**Comment by stefanfriedrich** [comment]
any news on this? we are running into the same problem.
problem is, endroid/qr-code is used by another plugin in a newer version (4).
