### ISSUE TITLE
URL opening

### ISSUE THREAD

**Issue by EternalBlack** [KuriousAgency/craft-qrcode#3]
I'm trying to use the plugin to generate a QR code link to URL but unfortunately it seems like there always are `"` at the start and end resulting in not mobile readable QR-Codes.

This is what I'm using
```
{% set qrURL = craft.app.request.absoluteUrl|url_encode %}
{% set qr = craft.qrcode.generate(qrURL) %}
{{ qrURL }}
</br>
<img src="{{ qr }}">
```
Removing `|url_encode` results in the same problem.

What the camera reads is `"https://example.com/"`

**Comment by samuelbirch** [comment]
this should now be fixed in v1.0.2.
